@hostname = ubuntu-pi4
@port = 8081
@host = {{hostname}}:{{port}}

###
GET http://{{host}}/filter-events

###
GET http://{{host}}/filter-events/1

###
POST http://{{host}}/filter-events
content-type: application/json

{
    "name": "hallo",
    "message": "echo"
}