@hostname = ubuntu-pi4
@port = 8081
#@hostname = localhost
#@port = 8080
@host = {{hostname}}:{{port}}

### get all
GET http://{{host}}/filter-events

### get single
GET http://{{host}}/filter-events/2

### get last
GET http://{{host}}/filter-events/-1

###
POST http://{{host}}/filter-events
content-type: application/json

{
    "name": "hallo",
    "message": "echo"
}